<a href="https://colab.research.google.com/github/LucasPequenoSterzeck/Treinos_Gerais_Python_LPS/blob/main/Python_Bibliotecas_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução a bibliotecas do Python e a biblioteca Pandas.

<img src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Falicantemag.com%2Fwp-content%2Fuploads%2F2016%2F10%2Fbiblioteca.jpg&f=1&nofb=1&ipt=6841a1e53b4eb47e3a80a3173cd31faef7e3bba289053df78a228ea253639e9b&ipo=images' width='500'>

Este notebook será dividido em dois segmentos:
- 1º O que são bibliotecas do Python;
- 2º Biblioteca Pandas e como usá-la.

# **1º Bloco: Bibliotecas do Python**

## 1.1 - O que são bibliotecas? 
As bibliotecas do Python são conjuntos de módulos e ferramentas que você pode usar para realizar tarefas específicas em seus programas Python. Elas fornecem uma ampla variedade de funcionalidades, como acesso a banco de dados, manipulação de imagens, manipulação de arquivos, criação de gráficos e muito mais. 

## 1.2 - Porque devo usar bibliotecas?

Existem várias razões pelas quais você pode querer usar bibliotecas no Python:

> **Economia de tempo: **as bibliotecas do Python são criadas por desenvolvedores experientes que já implementaram muitas das funcionalidades comuns que você pode precisar em seus programas. Ao usar uma biblioteca, você pode economizar tempo ao não ter que reimplementar essas funcionalidades do zero.

> **Qualidade:** as bibliotecas do Python são geralmente testadas e otimizadas por uma comunidade de desenvolvedores, o que as torna confiáveis e eficientes.

> **Reutilização de código:** ao usar uma biblioteca, você pode facilmente reutilizar o código em vários projetos diferentes, o que pode ajudar a economizar tempo e esforço.

> **Comunidade:** ao usar uma biblioteca popular, você pode facilmente obter ajuda e suporte da comunidade de desenvolvedores que a usam.

> **Integração:** as bibliotecas do Python geralmente se integram facilmente com outras bibliotecas e ferramentas, o que pode tornar mais fácil criar soluções de software mais amplas e complexas.

## 1.3 - Algumas bibliotecas do Python:
Algumas das bibliotecas mais populares do Python incluem:

> **NumPy**: fornece suporte para a criação e manipulação de arrays multidimensionais e matrizes de números.

> **Pandas**: fornece estruturas de dados e ferramentas de análise de dados para a manipulação e análise de dados tabulares.

> **Matplotlib**: permite a criação de gráficos e visualizações de dados em 2D.

> **SciPy**: é uma biblioteca de ciência de dados e ciência de computação que fornece muitas ferramentas avançadas para trabalhar com dados científicos.

Essas são apenas algumas das muitas bibliotecas disponíveis para o Python. Existem muitas outras bibliotecas disponíveis para atender a uma ampla variedade de necessidades e propósitos.

# **2º Bloco: Biblioteca Pandas**

## 2.1 - Para que serve a biblioteca Pandas:

A biblioteca Pandas do Python é uma ferramenta poderosa para análise e manipulação de dados. Ela fornece estruturas de dados e ferramentas para a manipulação de dados tabulares em formato de planilha, como aqueles que você encontraria em uma planilha do Excel ou em um banco de dados relacional. Algumas das principais funcionalidades da biblioteca Pandas incluem:

> Leitura e gravação de dados em vários formatos, incluindo CSV, Excel, JSON e SQL.

> Limpeza de dados e manipulação de valores ausentes.

> Agrupamento e agregação de dados.

> Fusão e junção de conjuntos de dados.

> Transformação de dados através de mapeamento e aplicação de funções.

> Visualização de dados através da integração com a biblioteca Matplotlib.

## 2.2 - Em qual área é mais utilizado o Pandas?

A biblioteca Pandas é amplamente utilizada em muitas áreas, como ciência de dados, finanças e análise de dados empresariais. Ela é conhecida por ser fácil de usar e por fornecer um alto desempenho para trabalhar com conjuntos de dados de tamanho médio a grande.

## 2.3 - Exemplo prático do pandas:

A seguir iremos implementar diversas célular com códigos Python, leia as observações presentes após o símbolo '#', e para executar o código clique no botão "PLAY" presente no canto superior esquerdo de cada célula.

In [2]:
# Comando para instalar o Pandas no Python
!pip install pandas

# Comando para importar a biblioteca Pandas no Python
import pandas as pd
# Por convenção sempre importamos o Pandas com a abreviação 'pd'.

In [6]:
# Lê um conjunto de dados de um arquivo CSV e armazena em um DataFrame
df = pd.read_csv('https://raw.githubusercontent.com/LucasPequenoSterzeck/Treinos_Gerais_Python_LPS/main/exemplo_csv.csv', sep=';')

# Exibe as primeiras linhas do DataFrame
display(df)

   Frota     Apontamento Ultima Comunicacao
0  12357   208 - Perdido   03/01/2023 19:31
1  32185  127 - Auxiliar   03/01/2023 19:31
2   4458  87 - Produtivo   03/01/2023 19:31
3  19885   209 - Perdido   03/01/2023 19:31
4  71470  128 - Auxiliar   03/01/2023 19:31

In [8]:
# Seleciona uma coluna do DataFrame
coluna_um = df['Frota']

display(coluna_um)

0    12357
1    32185
2     4458
3    19885
4    71470
5    44350
6     1712
Name: Frota, dtype: int64

In [13]:
# Seleciona várias colunas do DataFrame
colunas = df[['Frota', 'Ultima Comunicacao']]

display(colunas)

   Frota Ultima Comunicacao
0  12357   03/01/2023 19:31
1  32185   03/01/2023 19:31
2   4458   03/01/2023 19:31
3  19885   03/01/2023 19:31
4  71470   03/01/2023 19:31
5  44350   03/01/2023 19:31
6   1712   03/01/2023 19:31

In [12]:
# Filtra os dados do DataFrame usando uma condição
filtro = df['Frota'] > 20000
filtrado = df[filtro]

display(filtrado)

   Frota     Apontamento Ultima Comunicacao
1  32185  127 - Auxiliar   03/01/2023 19:31
4  71470  128 - Auxiliar   03/01/2023 19:31
5  44350  88 - Produtivo   03/01/2023 19:31

In [14]:
# Reordena os dados pelo valor de uma coluna e aplica uma agregação
reordenado = df.sort_values(by='Frota')

# Abaixo visualização da reordenação da frota menor até a frota maior
display(reordenado)

   Frota     Apontamento Ultima Comunicacao
6   1712   210 - Perdido   03/01/2023 19:31
2   4458  87 - Produtivo   03/01/2023 19:31
0  12357   208 - Perdido   03/01/2023 19:31
3  19885   209 - Perdido   03/01/2023 19:31
1  32185  127 - Auxiliar   03/01/2023 19:31
5  44350  88 - Produtivo   03/01/2023 19:31
4  71470  128 - Auxiliar   03/01/2023 19:31

In [15]:
# Grava o DataFrame em um arquivo CSV
df.to_csv('meus_dados_processados.csv', index=False)